[2025-04-05T10:45:18.705+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T10:45:18.760+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T10:45:18.770+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T10:45:18.771+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T10:45:18.787+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T10:45:18.797+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=321) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T10:45:18.796+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'load_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmp8elzkqm_']
[2025-04-05T10:45:18.798+0000] {standard_task_runner.py:63} INFO - Started process 345 to run task
[2025-04-05T10:45:18.799+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask load_data
[2025-04-05T10:45:18.819+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T10:45:18.863+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host d56545bf874e
[2025-04-05T10:45:18.969+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T10:45:18.970+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T10:45:18.989+0000] {logging_mixin.py:188} INFO - Error loading data to DuckDB: IO Error: Cannot open file "/opt/***/new/data/historical_bitcoin.db": No such file or directory
[2025-04-05T10:45:18.990+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T10:45:18.991+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T10:45:19.005+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=load_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T104518, end_date=20250405T104519
[2025-04-05T10:45:19.056+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T10:45:19.076+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T10:45:19.080+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T11:10:27.753+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T11:10:27.791+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T11:10:27.800+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T11:10:27.801+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T11:10:27.824+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T11:10:27.834+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'load_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmp3llpjp2y']
[2025-04-05T11:10:27.835+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=382) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T11:10:27.837+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask load_data
[2025-04-05T11:10:27.838+0000] {standard_task_runner.py:63} INFO - Started process 407 to run task
[2025-04-05T11:10:27.862+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T11:10:27.911+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host 1b61a216da47
[2025-04-05T11:10:28.007+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T11:10:28.009+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T11:10:28.029+0000] {logging_mixin.py:188} INFO - Error loading data to DuckDB: IO Error: Cannot open file "/opt/***/new/data/historical_bitcoin.db": No such file or directory
[2025-04-05T11:10:28.030+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T11:10:28.032+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T11:10:28.047+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=load_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T111027, end_date=20250405T111028
[2025-04-05T11:10:28.104+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T11:10:28.144+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T11:10:28.149+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T15:55:36.222+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T15:55:36.259+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T15:55:36.268+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T15:55:36.268+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T15:55:36.280+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T15:55:36.288+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=563) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T15:55:36.288+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'load_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpy6ndh42x']
[2025-04-05T15:55:36.289+0000] {standard_task_runner.py:63} INFO - Started process 587 to run task
[2025-04-05T15:55:36.289+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask load_data
[2025-04-05T15:55:36.309+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T15:55:36.352+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host a4017603cc0b
[2025-04-05T15:55:36.445+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T15:55:36.446+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T15:55:36.465+0000] {logging_mixin.py:188} INFO - Error loading data to DuckDB: IO Error: Cannot open file "/opt/***/new/data/historical_bitcoin.db": No such file or directory
[2025-04-05T15:55:36.465+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T15:55:36.467+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T15:55:36.480+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=load_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T155536, end_date=20250405T155536
[2025-04-05T15:55:36.511+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T15:55:36.532+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T15:55:36.535+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T16:31:56.546+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T16:31:56.582+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T16:31:56.589+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T16:31:56.590+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T16:31:56.603+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T16:31:56.611+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=318) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T16:31:56.611+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'load_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpksd1umpg']
[2025-04-05T16:31:56.612+0000] {standard_task_runner.py:63} INFO - Started process 341 to run task
[2025-04-05T16:31:56.612+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask load_data
[2025-04-05T16:31:56.630+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T16:31:56.675+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host d060e19f414c
[2025-04-05T16:31:56.794+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T16:31:56.796+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T16:31:56.825+0000] {logging_mixin.py:188} INFO - Error loading data to DuckDB: IO Error: Cannot open file "/opt/***/new/data/historical_bitcoin.db": No such file or directory
[2025-04-05T16:31:56.826+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T16:31:56.829+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T16:31:56.866+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=load_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T163156, end_date=20250405T163156
[2025-04-05T16:31:56.951+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T16:31:56.970+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T16:31:56.973+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T16:41:18.254+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T16:41:18.302+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T16:41:18.315+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T16:41:18.316+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T16:41:18.336+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T16:41:18.348+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=279) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T16:41:18.347+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'load_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpg8cbq7rf']
[2025-04-05T16:41:18.350+0000] {standard_task_runner.py:63} INFO - Started process 302 to run task
[2025-04-05T16:41:18.350+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask load_data
[2025-04-05T16:41:18.375+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T16:41:18.430+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host 658edd075563
[2025-04-05T16:41:18.554+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T16:41:18.555+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T16:41:18.587+0000] {logging_mixin.py:188} INFO - Error loading data to DuckDB: IO Error: Cannot open file "/opt/***/new/data/historical_bitcoin.db": No such file or directory
[2025-04-05T16:41:18.589+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T16:41:18.590+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T16:41:18.628+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=load_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T164118, end_date=20250405T164118
[2025-04-05T16:41:18.686+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T16:41:18.704+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T16:41:18.711+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T16:43:46.676+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T16:43:46.714+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T16:43:46.722+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T16:43:46.723+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T16:43:46.738+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T16:43:46.746+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=278) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T16:43:46.746+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'load_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmp7xw9qvm6']
[2025-04-05T16:43:46.748+0000] {standard_task_runner.py:63} INFO - Started process 290 to run task
[2025-04-05T16:43:46.748+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask load_data
[2025-04-05T16:43:46.769+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T16:43:46.815+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host 1f8025531576
[2025-04-05T16:43:46.920+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T16:43:46.922+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T16:43:46.941+0000] {logging_mixin.py:188} INFO - Error loading data to DuckDB: IO Error: Cannot open file "/opt/***/new/data/historical_bitcoin.db": No such file or directory
[2025-04-05T16:43:46.942+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T16:43:46.945+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T16:43:46.974+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=load_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T164346, end_date=20250405T164346
[2025-04-05T16:43:47.011+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T16:43:47.029+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T16:43:47.035+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T17:21:53.061+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T17:21:53.097+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T17:21:53.106+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T17:21:53.107+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T17:21:53.120+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T17:21:53.129+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=328) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T17:21:53.129+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'load_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpuapqrecy']
[2025-04-05T17:21:53.130+0000] {standard_task_runner.py:63} INFO - Started process 340 to run task
[2025-04-05T17:21:53.131+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask load_data
[2025-04-05T17:21:53.149+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T17:21:53.191+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host 3662cb577b20
[2025-04-05T17:21:53.284+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T17:21:53.285+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T17:21:53.302+0000] {logging_mixin.py:188} INFO - Error loading data to DuckDB: IO Error: Cannot open file "/opt/***/new/data/historical_bitcoin.db": No such file or directory
[2025-04-05T17:21:53.303+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T17:21:53.305+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T17:21:53.336+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=load_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T172153, end_date=20250405T172153
[2025-04-05T17:21:53.394+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T17:21:53.414+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T17:21:53.416+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T17:29:09.214+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T17:29:09.247+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T17:29:09.255+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T17:29:09.256+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T17:29:09.269+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T17:29:09.276+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'load_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmp9uqt1du1']
[2025-04-05T17:29:09.276+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=320) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T17:29:09.278+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask load_data
[2025-04-05T17:29:09.278+0000] {standard_task_runner.py:63} INFO - Started process 332 to run task
[2025-04-05T17:29:09.294+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T17:29:09.334+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.load_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host de3d8b486e6c
[2025-04-05T17:29:09.435+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T17:29:09.436+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T17:29:09.454+0000] {logging_mixin.py:188} INFO - Error loading data to DuckDB: IO Error: Cannot open file "/opt/***/new/data/historical_bitcoin.db": No such file or directory
[2025-04-05T17:29:09.455+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T17:29:09.456+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T17:29:09.481+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=load_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T172909, end_date=20250405T172909
[2025-04-05T17:29:09.536+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T17:29:09.586+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T17:29:09.588+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
