[2025-04-05T11:10:22.653+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T11:10:22.689+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data manual__2025-04-05T11:10:21.697137+00:00 [queued]>
[2025-04-05T11:10:22.696+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data manual__2025-04-05T11:10:21.697137+00:00 [queued]>
[2025-04-05T11:10:22.698+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T11:10:22.714+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_coin_data> on 2025-04-05 11:10:21.697137+00:00
[2025-04-05T11:10:22.722+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'get_coin_data', 'manual__2025-04-05T11:10:21.697137+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpkvjgj6or']
[2025-04-05T11:10:22.723+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=304) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T11:10:22.724+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask get_coin_data
[2025-04-05T11:10:22.725+0000] {standard_task_runner.py:63} INFO - Started process 328 to run task
[2025-04-05T11:10:22.742+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T11:10:22.784+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.get_coin_data manual__2025-04-05T11:10:21.697137+00:00 [running]> on host 1b61a216da47
[2025-04-05T11:10:22.904+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='get_coin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T11:10:21.697137+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-05T11:10:21.697137+00:00'
[2025-04-05T11:10:22.906+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T11:10:23.132+0000] {logging_mixin.py:188} INFO - Error fetching data: 429 Client Error: Too Many Requests for url: https://api.coincap.io/v2/assets/bitcoin/history?interval=h1&start=1609459200000&end=1609545599999
[2025-04-05T11:10:23.134+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T11:10:23.136+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T11:10:23.152+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=get_coin_data, run_id=manual__2025-04-05T11:10:21.697137+00:00, execution_date=20250405T111021, start_date=20250405T111022, end_date=20250405T111023
[2025-04-05T11:10:23.222+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T11:10:23.263+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-05T11:10:23.271+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
