[2025-04-05T16:31:53.051+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T16:31:53.087+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data manual__2025-04-05T16:31:51.978624+00:00 [queued]>
[2025-04-05T16:31:53.095+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data manual__2025-04-05T16:31:51.978624+00:00 [queued]>
[2025-04-05T16:31:53.096+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T16:31:53.109+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_coin_data> on 2025-04-05 16:31:51.978624+00:00
[2025-04-05T16:31:53.117+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=239) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T16:31:53.117+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'get_coin_data', 'manual__2025-04-05T16:31:51.978624+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpnwr4ue66']
[2025-04-05T16:31:53.118+0000] {standard_task_runner.py:63} INFO - Started process 263 to run task
[2025-04-05T16:31:53.118+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask get_coin_data
[2025-04-05T16:31:53.137+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T16:31:53.176+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.get_coin_data manual__2025-04-05T16:31:51.978624+00:00 [running]> on host d060e19f414c
[2025-04-05T16:31:53.272+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='get_coin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T16:31:51.978624+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-05T16:31:51.978624+00:00'
[2025-04-05T16:31:53.274+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T16:31:53.470+0000] {logging_mixin.py:188} INFO - Error fetching data: 429 Client Error: Too Many Requests for url: https://api.coincap.io/v2/assets/bitcoin/history?interval=h1&start=1609459200000&end=1609545599999
[2025-04-05T16:31:53.472+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T16:31:53.474+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T16:31:53.489+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=get_coin_data, run_id=manual__2025-04-05T16:31:51.978624+00:00, execution_date=20250405T163151, start_date=20250405T163153, end_date=20250405T163153
[2025-04-05T16:31:53.536+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T16:31:53.566+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T16:31:53.569+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
