[2025-04-01T20:19:06.368+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-01T20:19:06.405+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-03-31T00:00:00+00:00 [queued]>
[2025-04-01T20:19:06.412+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.load_data scheduled__2025-03-31T00:00:00+00:00 [queued]>
[2025-04-01T20:19:06.413+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-01T20:19:06.427+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-03-31 00:00:00+00:00
[2025-04-01T20:19:06.435+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'load_data', 'scheduled__2025-03-31T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpp97l9_wt']
[2025-04-01T20:19:06.435+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=353) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-01T20:19:06.436+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask load_data
[2025-04-01T20:19:06.437+0000] {standard_task_runner.py:63} INFO - Started process 376 to run task
[2025-04-01T20:19:06.455+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-01T20:19:06.497+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.load_data scheduled__2025-03-31T00:00:00+00:00 [running]> on host 32b02857b00b
[2025-04-01T20:19:06.588+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-31T00:00:00+00:00'
[2025-04-01T20:19:06.589+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-01T20:19:06.608+0000] {logging_mixin.py:188} INFO - Error loading data to DuckDB: IO Error: Cannot open file "/opt/***/new/data/historical_bitcoin.db": No such file or directory
[2025-04-01T20:19:06.609+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-01T20:19:06.610+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-01T20:19:06.623+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=load_data, run_id=scheduled__2025-03-31T00:00:00+00:00, execution_date=20250331T000000, start_date=20250401T201906, end_date=20250401T201906
[2025-04-01T20:19:06.650+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-01T20:19:06.668+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-01T20:19:06.670+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
